[Icon Theme]
Name=STARK OS
Comment=Detailed holographic instruments with optical sizes
Inherits=breeze-dark,breeze,hicolor
Directories=16x16/apps,16x16/places,16x16/devices,16x16/mimetypes,16x16/actions,16x16/status,22x22/apps,22x22/places,22x22/devices,22x22/mimetypes,22x22/actions,22x22/status,scalable/apps,scalable/places,scalable/devices,scalable/mimetypes,scalable/actions,scalable/status

[16x16/apps]
Size=16
Context=Applications
Type=Fixed

[16x16/places]
Size=16
Context=Places
Type=Fixed

[16x16/devices]
Size=16
Context=Devices
Type=Fixed

[16x16/mimetypes]
Size=16
Context=MimeTypes
Type=Fixed

[16x16/actions]
Size=16
Context=Actions
Type=Fixed

[16x16/status]
Size=16
Context=Status
Type=Fixed

[22x22/apps]
Size=22
Context=Applications
Type=Fixed

[22x22/places]
Size=22
Context=Places
Type=Fixed

[22x22/devices]
Size=22
Context=Devices
Type=Fixed

[22x22/mimetypes]
Size=22
Context=MimeTypes
Type=Fixed

[22x22/actions]
Size=22
Context=Actions
Type=Fixed

[22x22/status]
Size=22
Context=Status
Type=Fixed

[scalable/apps]
Size=128
Context=Applications
Type=Scalable
MinSize=32
MaxSize=512

[scalable/places]
Size=128
Context=Places
Type=Scalable
MinSize=32
MaxSize=512

[scalable/devices]
Size=128
Context=Devices
Type=Scalable
MinSize=32
MaxSize=512

[scalable/mimetypes]
Size=128
Context=MimeTypes
Type=Scalable
MinSize=32
MaxSize=512

[scalable/actions]
Size=128
Context=Actions
Type=Scalable
MinSize=32
MaxSize=512

[scalable/status]
Size=128
Context=Status
Type=Scalable
MinSize=32
MaxSize=512
