# Optional Kitty include; STARK OS color profile
font_family Share Tech Mono
font_size 10.0
background #03101a
foreground #d9f4ff
cursor #5fe3ff
selection_background #12546a
selection_foreground #d8f8ff
color0 #061826
color1 #ff4d5e
color2 #6dffb3
color3 #ffb347
color4 #2a8fb0
color5 #b48cff
color6 #5fe3ff
color7 #d9f4ff
color8 #103044
color9 #ff7a86
color10 #a0ffcd
color11 #ffcd82
color12 #5ab4dc
color13 #cdb4ff
color14 #d8f8ff
color15 #ffffff
